
export enum PostConst {
    POSTING_SUCCESSFUL = 'POSTING_SUCCESSFUL',
    POSTING_FAILED = 'POSTING_FAILED',
    POSTING_IN_PROCESS = "POSTING_IN_PROCESS",
}

export enum REQ {
    POST = "POST",
    GET = "GET",
    PATCH = "PATCH"
}